<?php

namespace App\Http\Requests\User\Settings;

use Illuminate\Foundation\Http\FormRequest;

class ChangeUserPasswordRequest extends FormRequest
{
    /**
     * @OA\Schema(
     *     title="Change User password",
     *     description="Change User password request",
     *     schema="ChangeUserPasswordRequestSchema",
     *     required={"password", "passwordConfirmation", "newPassword"},
     *      @OA\Property(
     *          property="password",
     *          type="string",
     *          example="password",
     *          title="Password of the user.",
     *     ),
     *      @OA\Property(
     *          property="newPassword",
     *          type="string",
     *          example="password",
     *          title="New Password of the user.",
     *     ),
     *      @OA\Property(
     *          property="newPasswordConfirmation",
     *          type="string",
     *          example="password",
     *          title="Password Confirmation of the user.",
     *     ),
     * )
     *
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'password' => [
                'required',
                'string',
                'min:6',
            ],
            'newPassword' => [
                'required',
                'string',
                'min:6',
                'same:newPasswordConfirmation',
            ],
            'newPasswordConfirmation' => [
                'required',
                'string',
                'min:6',
            ],
        ];
    }

    /**
     * @OA\Schema(
     *     title="Change User password validation",
     *     description="Change User password validation messages",
     *     schema="ChangeUserPasswordRequestMessagesSchema",
     *      @OA\Property(
     *          property="password",
     *          type="string",
     *          example={"The password field is required.", "The password should be string."}
     *      ),
     *      @OA\Property(
     *          property="passwordConfirmation",
     *          type="string",
     *          example={"The passwordConfirmation field is required.", "The passwordConfirmation should be string."}
     *      ),
     *      @OA\Property(
     *          property="newPassword",
     *          type="string",
     *          example={"The newPassword field is required.", "The newPassword should be string."}
     *      ),
     * )
     *
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
