<?php

namespace App\Http\Requests\Cart;

use App\Rules\Cart\CountNumberAndTypeRule;
use App\Rules\Cart\NotAvailableCountRule;
use Illuminate\Foundation\Http\FormRequest;

class AddToCartRequest extends FormRequest
{

    /**
     * @OA\Schema(
     *     title="Add To Cart",
     *     description="Add to cart request",
     *     schema="AddToCartRequestSchema",
     *     required={"id", "count"},
     * 	   @OA\Property(
     *          property="id",
     *          type="string",
     *          example="0178bfed-17d5-34f8-88cf-299b3281a2c1",
     *          title="ID of the product."
     *     ),
     * 	   @OA\Property(
     *          property="count",
     *          type="number",
     *          example="1"
     *     ),
     * )
     *
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'id' => [
                'required',
                'string',
                'exists:products,uuid',
            ],
            'count' => [
                'required',
                'numeric',
                new CountNumberAndTypeRule,
            ],
        ];
    }

    /**
     * @OA\Schema(
     *     title="Add To Cart",
     *     description="Add To Cart validation messages",
     *     schema="AddToCartRequestMessagesSchema",
     * 	   @OA\Property(
     *          property="id",
     *          type="string",
     *          example={"The id field is required.", "The selected id is invalid."},
     *     ),
     * 	   @OA\Property(
     *          property="count",
     *                 type="string",
     *                 example={"The count field is required.", "The count should be a numeric."}
     *      )
     * )
     *
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
