<?php

namespace App\Http\Requests\Product\Favorites;

use Illuminate\Foundation\Http\FormRequest;

class CreateFavoritesProductsRequest extends FormRequest
{
    /**
     * @OA\Schema(
     *     title="Create Favorites Products",
     *     description="Create Favorites Products request",
     *     schema="CreateFavoritesProductsRequestSchema",
     *     required={"products"},
     * 	   @OA\Property(
     *          property="products",
     *          type="array",
     *          @OA\Items(
     *              type="string",
     *              example={"3f583ccc-6ca7-473f-8978-94755ab94504", "bb172977-7c3e-4672-bb9b-41115e7b6b86", "ab8e723c-5b74-4084-9a2e-ab574972f912"}
     *          )
     *     ),
     * )
     *
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'products' => [
                'required',
                'array',
            ],
            'products.*' => [
                'required',
                'string',
                'exists:products,uuid',
            ],
        ];
    }

    /**
     * @OA\Schema(
     *     title="Create Favorites Products Request Messages",
     *     description="Create Favorites Products Request messages",
     *     schema="CreateFavoritesProductsRequestMessagesSchema",
     * 	   @OA\Property(
     *          property="products",
     *          type="string",
     *          example={"The id field is required.", "The product elemnt is invalid."},
     *     ),
     * );
     *
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
